[package]
name = "rust_worker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
tonic = "0.8"
prost = "0.11"
prost-types = "0.11"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
google-cloud-pubsub = { path = "../../../../google-cloud-rust/src/pubsub" }
num_cpus = "1.0"
bytes = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
futures = "0.3.31"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'

[build-dependencies]
tonic-build = "0.8"
